import { chmod, copyFile, writeFile } from 'node:fs/promises'
import { join } from 'node:path'

/**
 * Installs the `sauron` CLI into the app's bin directory as a shell shim that runs the bundled
 * CLI script with Electron's own Node (ELECTRON_RUN_AS_NODE). Works in development and when
 * packaged, and needs no system Node.
 */
export async function installCliShim(binDir: string, cliSource: string, execPath: string): Promise<string> {
  const script = join(binDir, 'sauron-cli.js')
  const shim = join(binDir, 'sauron')
  await copyFile(cliSource, script)
  const content = `#!/bin/sh
# Generated by Sauron. Runs the Sauron control CLI with the app's bundled Node runtime.
ELECTRON_RUN_AS_NODE=1 exec ${quote(execPath)} ${quote(script)} "$@"
`
  await writeFile(shim, content, 'utf8')
  await chmod(shim, 0o755)
  return shim
}

function quote(s: string): string {
  return `'${s.replace(/'/g, `'\\''`)}'`
}
