import { chmod, copyFile, cp, rm, writeFile } from 'node:fs/promises'
import { existsSync } from 'node:fs'
import { dirname, join } from 'node:path'

/**
 * Installs the `sauron` CLI into the app's bin directory as a shell shim that runs the bundled
 * CLI script with Electron's own Node (ELECTRON_RUN_AS_NODE). Works in development and when
 * packaged, and needs no system Node.
 */
export async function installCliShim(binDir: string, cliSource: string, execPath: string): Promise<string> {
  const script = join(binDir, 'sauron-cli.js')
  const shim = join(binDir, 'sauron')
  await copyFile(cliSource, script)
  // The bundler splits code the CLI loads lazily (the background-job runner) into sibling
  // chunks, imported by relative path; they have to travel with the script or `sauron job`
  // fails to resolve them. Replaced wholesale so a stale chunk from an old build cannot linger.
  const chunks = join(dirname(cliSource), 'chunks')
  if (existsSync(chunks)) {
    await rm(join(binDir, 'chunks'), { recursive: true, force: true })
    await cp(chunks, join(binDir, 'chunks'), { recursive: true })
  }
  const content = `#!/bin/sh
# Generated by Sauron. Runs the Sauron control CLI with the app's bundled Node runtime.
ELECTRON_RUN_AS_NODE=1 exec ${quote(execPath)} ${quote(script)} "$@"
`
  await writeFile(shim, content, 'utf8')
  await chmod(shim, 0o755)
  return shim
}

function quote(s: string): string {
  return `'${s.replace(/'/g, `'\\''`)}'`
}
