import { chmod, readFile, rename, unlink, writeFile } from 'node:fs/promises'
import { existsSync } from 'node:fs'
import { join } from 'node:path'
import { runCommand } from './command'
import { shellQuote } from '@shared/tmux-args'
import { SauronError } from '@shared/types'

/**
 * Records commits, and triggers background jobs, by way of a `post-commit` hook in each project.
 *
 * The hook inherits the environment of whatever invoked git, so `SAURON_SESSION_ID` is present
 * exactly when the commit came from a managed session and absent otherwise; it runs the CLI
 * either way, since a job may be triggered by a commit the user made by hand. That makes it immune
 * to PATH rewriting, which a shim on PATH is not: shell startup files routinely prepend to PATH
 * and push anything Sauron puts there behind the real git.
 *
 * Linked worktrees resolve hooks to the main checkout's hook directory, so one install per
 * project also covers every worktree Sauron creates for it.
 */

/** Marks our script so an install is idempotent and a foreign hook is never mistaken for ours. */
const MARKER = '# sauron-post-commit-hook'

/** Where an existing third-party hook is kept so our hook can chain to it. */
const CHAINED_SUFFIX = '.pre-sauron'

/**
 * Both binaries are absolute: a hook must not depend on PATH, which is the whole reason this
 * exists. git runs post-commit from the top of the working tree, so `$PWD` names the checkout
 * or worktree the commit was made in.
 */
export function postCommitScript(sauronBin: string, gitBin: string): string {
  return `#!/bin/sh
${MARKER}
# Generated by Sauron. Reports the commit (attribution when made inside a managed session,
# and background-job triggers for any commit), then runs whatever post-commit hook was here
# before. Never fails a commit: every path exits 0.
hash=$(${shellQuote(gitBin)} rev-parse HEAD 2>/dev/null)
if [ -n "$hash" ]; then
  ${shellQuote(sauronBin)} commit-hook --hash "$hash" --cwd "$PWD" >/dev/null 2>&1 || true
fi
chained=$(dirname "$0")/post-commit${CHAINED_SUFFIX}
if [ -x "$chained" ]; then
  "$chained" "$@" || true
fi
exit 0
`
}

/** Resolves a repository's hook directory, honouring core.hooksPath and linked worktrees. */
export async function hooksDirectory(git: string, repoPath: string): Promise<string> {
  const result = await runCommand(git, ['rev-parse', '--git-path', 'hooks'], { cwd: repoPath })
  if (result.code !== 0 || !result.stdout.trim()) {
    throw new SauronError('command_failed', `git rev-parse --git-path hooks: ${result.stderr.trim()}`)
  }
  const dir = result.stdout.trim()
  return dir.startsWith('/') ? dir : join(repoPath, dir)
}

async function isOurs(file: string): Promise<boolean> {
  return (await readFile(file, 'utf8').catch(() => '')).includes(MARKER)
}

/**
 * Installs the hook, preserving any hook already there by moving it aside and chaining to it.
 * Safe to call repeatedly; the script is rewritten so a changed binary path takes effect.
 */
export async function installPostCommitHook(git: string, repoPath: string, sauronBin: string): Promise<void> {
  const dir = await hooksDirectory(git, repoPath)
  const hook = join(dir, 'post-commit')
  const chained = `${hook}${CHAINED_SUFFIX}`
  if (existsSync(hook) && !(await isOurs(hook))) {
    // Someone else's hook. Keep it and run it from ours rather than silently replacing it.
    if (existsSync(chained)) {
      throw new SauronError('invalid_state', `${chained} already exists; refusing to overwrite a saved hook.`)
    }
    await rename(hook, chained)
  }
  await writeFile(hook, postCommitScript(sauronBin, git), 'utf8')
  await chmod(hook, 0o755)
}

/** Removes our hook and restores whatever it displaced. Leaves a foreign hook untouched. */
export async function removePostCommitHook(git: string, repoPath: string): Promise<void> {
  const dir = await hooksDirectory(git, repoPath)
  const hook = join(dir, 'post-commit')
  const chained = `${hook}${CHAINED_SUFFIX}`
  if (existsSync(hook)) {
    if (!(await isOurs(hook))) return
    await unlink(hook)
  }
  if (existsSync(chained)) await rename(chained, hook)
}
