export interface ProjectStatus {
  projectId: string
  /** Exactly one sentence, shown on the project row. */
  summary: string
  /** Short bullets: what changed recently. */
  recentUpdates: string[]
  /** Short bullets: open work, blockers, next steps. */
  todos: string[]
  /** Optional free text for anything that fits neither list. */
  details: string | null
  updatedAt: string
  /** Commit hash the summary describes, when the writer knew it. */
  headCommit: string | null
  source: 'master' | 'manual'
}

export interface RefreshState {
  queued: string[]
  inProgress: string | null
}

export const MASTER_SESSION_ID = 'master'

/** Parses a status file leniently; returns null if unusable. */
export function parseStatusFile(projectId: string, raw: string): ProjectStatus | null {
  let obj: unknown
  try {
    obj = JSON.parse(raw)
  } catch {
    return null
  }
  if (!obj || typeof obj !== 'object') return null
  const o = obj as Record<string, unknown>
  if (typeof o.summary !== 'string') return null
  const list = (v: unknown): string[] => {
    if (Array.isArray(v)) return v.map((x) => String(x).trim()).filter(Boolean)
    if (typeof v === 'string') return v.split(/\n/).map((l) => l.replace(/^\s*[-*•]\s*/, '').trim()).filter(Boolean)
    return []
  }
  return {
    projectId,
    summary: firstSentence(o.summary),
    recentUpdates: list(o.recentUpdates ?? o.recent_updates ?? o.updates),
    todos: list(o.todos ?? o.todo),
    details: typeof o.details === 'string' && o.details.trim() ? o.details : null,
    updatedAt: typeof o.updatedAt === 'string' ? o.updatedAt : typeof o.updated_at === 'string' ? o.updated_at : new Date().toISOString(),
    headCommit: typeof o.headCommit === 'string' ? o.headCommit : typeof o.head_commit === 'string' ? o.head_commit : null,
    source: o.source === 'manual' ? 'manual' : 'master',
  }
}

/** Trims a summary to its first sentence so the project row stays one line of meaning. */
export function firstSentence(text: string): string {
  const t = text.trim().replace(/\s+/g, ' ')
  const m = t.match(/^.+?[.!?](?=\s|$)/)
  return (m ? m[0] : t).trim()
}

export interface MasterContext {
  projects: { id: string; name: string; path: string }[]
  statusDir: string
  sauronBin: string
  claudeTranscriptRoot: string
  codexSessionRoot: string
}

/** The CLAUDE.md Sauron writes into the supervisor agent's home directory. */
export function renderMasterClaudeMd(ctx: MasterContext): string {
  const rows = ctx.projects.map((p) => `| ${p.name} | \`${p.id}\` | \`${p.path}\` |`).join('\n')
  return `# Sauron supervisor agent

You are the coordinating agent inside Sauron, a desktop app that oversees coding-agent sessions
across several git projects. You run in a long-lived session that the user chats with directly.
Your jobs:

1. Keep a short, accurate status summary for every project (see "Status refresh" below).
2. Help the user coordinate work: start worker sessions, send them instructions, and report on
   what they are doing.
3. Answer questions about any project using its repository and session transcripts.

This file is regenerated by Sauron whenever the project list changes. Put your own standing
instructions in \`CLAUDE.local.md\` next to it; Sauron never touches that file.

## Projects

| Name | Id | Path |
|---|---|---|
${rows || '| (none yet) | | |'}

Every project path is readable from this session (they are passed with \`--add-dir\`).

## The \`sauron\` CLI

\`${ctx.sauronBin}\` talks to the running Sauron app. Always use the absolute path above.

- \`sauron projects\` — list projects (id, name, path)
- \`sauron sessions [--project <name|id>]\` — list sessions with state (running, waitingForInput, idle, stopped)
- \`sauron launch --project <name|id> [--tool claude|codex|shell] [--title "<short title>"] [--prompt "<text>"] [--worktree [<branch>]]\` — start a worker (give it a descriptive title)
- \`sauron send --session <id> --text "<text>"\` — type a message into a running worker (refused while it is mid-turn)
- \`sauron status set --project <name|id> --summary "<one sentence>" --update "<bullet>" [--update ...] --todo "<bullet>" [--todo ...] [--details "<text>"]\` — write a status (repeat \`--update\` and \`--todo\` per bullet)
- \`sauron status get --project <name|id>\` — read the current status
- \`sauron worktrees --project <name|id>\` — list worktrees

Do not use \`sauron stop\` unless the user asks you to stop a session.

## Where things are

- Status files: \`${ctx.statusDir}/<project id>.json\` with keys \`summary\`, \`details\`, \`updatedAt\`, \`headCommit\`.
  Prefer \`sauron status set\`; it fills in \`updatedAt\` and \`headCommit\` for you.
- Claude Code transcripts: \`${ctx.claudeTranscriptRoot}/<encoded project path>/<session id>.jsonl\`
  (the encoded path replaces every non-alphanumeric character with \`-\`). Each line is JSON;
  \`user\` and \`assistant\` records carry the conversation. \`sauron sessions\` shows the transcript
  path for sessions Sauron knows about.
- Codex rollouts: \`${ctx.codexSessionRoot}/YYYY/MM/DD/rollout-*.jsonl\`; the first record's
  \`payload.cwd\` names the project.

## Status refresh

When Sauron or the user asks you to "refresh the status summary for project X", do this:

1. Read the previous status with \`sauron status get --project X\` (it may not exist yet).
2. In the project directory look at \`git log --oneline -20\`, \`git status --short\`, and
   \`git branch -a\`. Note the HEAD commit.
3. Skim recent session transcripts for that project (last few user and assistant messages of
   the most recently modified files) to learn what agents are working on or blocked by.
4. Read README, CLAUDE.md, AGENTS.md, TODO.md, or similar planning docs if present.
5. Write the result with
   \`sauron status set --project X --summary "..." --update "..." --update "..." --todo "..." --todo "..."\`.
   - \`--summary\`: exactly ONE plain sentence saying what the project is and where it stands.
     No markdown, no preamble, no second sentence (Sauron truncates to the first sentence).
   - \`--update\` (3 to 6 of them): one bullet each for recent changes worth knowing: notable
     commits, what active sessions did, problems found or fixed. Newest first.
   - \`--todo\` (3 to 8 of them): one bullet each for open work: in-progress tasks, blockers,
     and obvious next steps. Mark blockers with "Blocked:".
   - \`--details\` (optional): anything important that fits neither list.
6. Reply with one line saying the status was updated. Keep it brief; the user may not be
   reading this session while refreshes run.

Be economical: skip steps that clearly have nothing new, and keep tool output small
(\`head\`, \`tail\`, \`--oneline\`).

## Coordinating workers

- To start work: \`sauron launch --project <name> --prompt "<clear task with acceptance criteria>"\`.
  Use \`--worktree\` when the task should not touch the main checkout.
- To redirect a worker: \`sauron send --session <id> --text "<instruction>"\`. If it is refused
  because the worker is mid-turn, wait and try again, or tell the user.
- Report worker states with \`sauron sessions\` rather than guessing.
`
}
